CREATE TABLE USER_INFO(
`USER_ID` int(11) NOT NULL AUTO_INCREMENT,
`NAME` varchar(50) NOT NULL,
`PASSWORD` varchar(30) NOT NULL,
PRIMARY KEY(`USER_ID`)
)ENGINE=INNODB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;

INSERT INTO USER_INFO(NAME, PASSWORD) VALUES('admin', '123456');